### ISSUE TITLE
Missing Files !?

### ISSUE THREAD

**Issue by Allan-Cao** [carykh/alignedCelebFaces#1]
`eigenvalues = np.load("eigenvalues.npy")
eigenvectors = np.load("eigenvectors.npy")`

It seems like those are necessary!? Are they missing due to the 25 mb limit?

**Comment by DoktorHolmes** [comment]
I'm getting this too.  :(

**Comment by carykh** [comment]
I just uploaded those files. it should be fixed now! ...hopefully
