### ISSUE TITLE
Error in the requirements.txt

### ISSUE THREAD

**Issue by VasilisThePikachu** [carykh/alignedCelebFaces#16]
yes i know there is a closed issue but i downgraded python but i got the same issue

`Could not find a version that satisfies the requirement tensorflow==1.12.0 (from -r requirements.txt (line 32)) (from versions: )
No matching distribution found for tensorflow==1.12.0 (from -r requirements.txt (line 32))`

**Comment by justarandomguyintheinternet** [comment]
Just replace "tensorflow==1.12.0" with "tensorflow==1.13.0rc1" in the requirements.txt file

**Comment by VasilisThePikachu** [comment]
> Just replace "tensorflow==1.12.0" with "tensorflow==1.13.0rc1" in the requirements.txt file

nope still same error

`Could not find a version that satisfies the requirement tensorflow==1.13.0rc1 (from -r requirements.txt (line 32)) (from versions: )
No matching distribution found for tensorflow==1.13.0rc1 (from -r requirements.txt (line 32))`

**Comment by justarandomguyintheinternet** [comment]
What version of Python are you using? Maybe its because you downgraded python?

**Comment by VasilisThePikachu** [comment]
> What version of Python are you using? Maybe its because you downgraded python?

i use 3.6.8 i will try updating and updating you to

**Comment by VasilisThePikachu** [comment]
> > What version of Python are you using? Maybe its because you downgraded python?
> 
> i use 3.6.8 i will try updating and updating you to

i updated to 3.7 but still getting the same error

**Comment by VasilisThePikachu** [comment]
any update on how to fix this?

**Comment by VasilisThePikachu** [comment]
reposted issue becose noone is ansering  me
