### ISSUE TITLE
Error in requirements.txt 2 repost

### ISSUE THREAD

**Issue by VasilisThePikachu** [carykh/alignedCelebFaces#17]
reposting because no one is answering me

what i tried:changed tensorflow=1.12.2 to tensorflow=1.12.0rc1
changing python version from latest to 3.6.8

`Could not find a version that satisfies the requirement tensorflow==1.13.0rc1 (from -r requirements.txt (line 32)) (from versions: )
No matching distribution found for tensorflow==1.13.0rc1 (from -r requirements.txt (line 32))`

**Comment by xAlpharax** [comment]
I know right? I tried every version so far, I'm running python 3.7.3 with all the files in the requirements.txt file still not working, sorry bc I can't help you...
