### ISSUE TITLE
oops.png not found

### ISSUE THREAD

**Issue by thkdlflghlsdghilr** [carykh/alignedCelebFaces#2]
File "final_face_slider_tool.py", line 285, in <module>
    oopsImage = pygame.image.load("oops.png")
pygame.error: Couldn't open oops.png

as a temp fix, I added a png file it with Shrek's face called oops.png and it worked! anytime I  misspell a name it shows his face so think it is a misspelling error image.

**Comment by carykh** [comment]
Just fixed it by uploading oops.png!

Also, I love that fix of replacing it with Shrek. Shrek is love, shrek is life, AND shrek is bug fixes.
