### ISSUE TITLE
A little issue with anyFaceEncoder.py

### ISSUE THREAD

**Issue by TheDarkBomber** [carykh/alignedCelebFaces#7]
I'm not on your computer, I don't have the same directory as you would lol
![image](https://user-images.githubusercontent.com/17354045/52534304-d31f3600-2d37-11e9-9f26-affd1d4ed202.png)

**Comment by louie-github** [comment]
Latest commit has fixed the problem :)
https://github.com/carykh/alignedCelebFaces/commit/f843088e5b344a6f6826788407e22359bd00d9a1
